### ISSUE TITLE
Scope down capi-operator-manager-role ClusterRole Permissions

### ISSUE THREAD

**Issue by keskanatala** [kubernetes-sigs/cluster-api-operator#104]
**User Story**

As a operator I would like to narrow the  `{"apiGroups": ["*"], "resources": ["*"], "verbs": ["*"]}` permissions used by `capi-operator-manager-role` for security reasons

**Detailed Description**

The * / * / * permissions requested are too broad for what the operator does. Can we scope these permissions down based on the objects that the operator creates?

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by Fedosin** [comment]
Hello @keskanatala! Unfortunately, there is a reason behind granting such broad permissions to our operator. As you may be aware, each cluster API provider has a unique set of Custom Resource Definitions (CRDs) - such as AWSMachineTemplates in CAPA, AzureManagedControlPlane in CAPZ, and so on. Additionally, these providers have their own RBAC permissions for their respective CRDs. To install these RBAC permissions, our operator must also has them; otherwise, we encounter a `user is attempting to grant RBAC permissions not currently held` error. This list of permissions is constantly evolving and cannot be predetermined or statically set, hence necessitating admin privileges for the operator.

If you have security concerns, there is a workaround. Rather than creating a `ClusterRoleBinding`, you can create a `RoleBinding` and specifically choose the namespaces where you install your providers. For example, if you want to install CAPA in `capa-system` namespace, just delete the permissive ClusterRoleBinding and apply this
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/core: capi-operator
  name: capi-operator-manager-rolebinding
  namespace: capa-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capi-operator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: capi-operator-system
```
After that operator will have admin permissions in a particular namespace rather then in the whole cluster.

I'm going to write a small document to describe this process in details.
