### ISSUE TITLE
Cluster API Operator keeps refetching data from the specified URL after successful provider installation

### ISSUE THREAD

**Issue by Fedosin** [kubernetes-sigs/cluster-api-operator#119]
**What steps did you take and what happened:**

Deploy a provider either from a predefined location or from a custom URL, make sure it is ready. For example:
```
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: capi-system
spec:
  version: v1.4.2
```

During each subsequent reconciliation (every 10 minutes by default), the operator will repeatedly fetch the configuration from GitHub. If a network issue arises or GitHub is unavailable, the operator will report an error and mark the provider as Unhealthy, even though it is functioning properly.

**What did you expect to happen:**

I would like the CAPI operator to retrieve the provider configuration solely during the initial installation. The status of my provider should not be impacted by any GitHub-related issues.

**Environment:**

- Cluster-api-operator version: main
- Cluster-api version: 1.4.2
- Minikube/KIND version: 0.26.2
- Kubernetes version: (use `kubectl version`): 1.26
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]
