### ISSUE TITLE
CRDs are not deleted when provider is removed

### ISSUE THREAD

**Issue by Fedosin** [kubernetes-sigs/cluster-api-operator#120]
**What steps did you take and what happened:**
1. Install a provider:
```
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: capi-system
spec:
  version: v1.4.2
```
2. Delete the provider
3. Ensure that all previously created CRDs from `cluster.x-k8s.io` are not deleted together with the provider.

**What did you expect to happen:**
All created resources should be removed.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-operator version: main
- Cluster-api version: 1.4.2
- Minikube/KIND version: 1.27
- Kubernetes version: (use `kubectl version`): 1.27
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]
