### ISSUE TITLE
Operator doesn't reconcile providers if their spec values changed

### ISSUE THREAD

**Issue by Fedosin** [kubernetes-sigs/cluster-api-operator#156]
**What steps did you take and what happened:**
Deploy a provider specifying some deployment arguments. For instance:
```yaml
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: InfrastructureProvider
metadata:
 name: aws
 namespace: capa-system
spec:
 version: v2.1.4
 secretName: aws-variables
 deployment:
   containers:
   - name: manager
     image:
         repository: "gcr.io/myregistry"
         name: "capa-controller"
         tag: "v2.1.4-foo"
```

Make sure that capa started successfully.

Update image in the provider spec:
```yaml
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: InfrastructureProvider
metadata:
 name: aws
 namespace: capa-system
spec:
 version: v2.1.4
 secretName: aws-variables
 deployment:
   containers:
   - name: manager
     image:
         repository: "gcr.io/myregistry"
         name: "capa-controller"
         tag: "v2.1.4-bar"
```

**What did you expect to happen:**

Operator should reconcile capa provider and update image for the deployment, but nothing happens.

**Environment:**

- Cluster-api-operator version: main

/kind bug
