### ISSUE TITLE
Feature gates are not injected into manager pod

### ISSUE THREAD

**Issue by Fedosin** [kubernetes-sigs/cluster-api-operator#172]
**What steps did you take and what happened:**

When I want to set custom feature gates for a provider manager, they are ignored

Example:

```yaml
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: CoreProvider
metadata:
  name: cluster-api
spec:
  version: v1.4.3
  manager:
    featureGates: 
      MachinePool: true
      ClusterResourceSet: true
      ClusterTopology: true
      RuntimeSDK: false
      LazyRestmapper: false    
```

For this manifests operator doesn't modify feature gates, and leaves default values, i.e. `--feature-gates=MachinePool=false,ClusterResourceSet=false,ClusterTopology=false,RuntimeSDK=false,LazyRestmapper=false`

**What did you expect to happen:**

Feature gates should be updated like `--feature-gates=MachinePool=true,ClusterResourceSet=true,ClusterTopology=true,RuntimeSDK=false,LazyRestmapper=false`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-operator version:
- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]
