### ISSUE TITLE
Customresource `spec.deployment` is only a limited subset

### ISSUE THREAD

**Issue by johanjk** [kubernetes-sigs/cluster-api-operator#310]
When setting overrides on the deployment, only the following parameters are available:

```yaml
spec:
  deployment: 
    affinity: [...]
    containers: [...]
    imagePullSecret: [...]
    nodeSelector: [...]
    replicas: [...]
    serviceAccountName: [...]
    tolerations: [...]
```

I would like to be able to configure, amongst other things `spec.strategy`. Could the operator allow the full deployment spec to be configured?

/kind feature
