### ISSUE TITLE
Missing clusterctl CustomResourceDefinition 

### ISSUE THREAD

**Issue by johanjk** [kubernetes-sigs/cluster-api-operator#311]
The operator does not install the [CustomResourceDefinitions](https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/config/crd/kustomization.yaml) normally created by `clusterctl init`.

Neither does it populate them, when creating `InfrastructureProvider` etc.

Leading us to do one of the following:
* Explicitly create the following:
  ```yaml
  apiVersion: clusterctl.cluster.x-k8s.io/v1alpha3
  kind: Provider
  [...]
  type: InfrastructureProvider
  ---
  apiVersion: operator.cluster.x-k8s.io/v1alpha2
  kind: InfrastructureProvider
  [...]
  ---
  [...]
  ```
  Which seems redundant.

* or having to run `clusterctl init` at least once in the cluster.

Otherwise, clusterctl move fails with the following:
```
> clusterctl move --to-kubeconfig kubeconfig
Error: failed to check providers in target cluster: [provider cluster-api not found in the target cluster]
```
/kind bug
