### ISSUE TITLE
Support adding featureGate flags with helm chart installation

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-operator#377]
**User Story**

As a operator I would like to be able to set the experimental flags for my cloud provider during installation so that I can enable those features on my cluster. 

**Detailed Description**
As a specific example, I need to enable `EXP_MACHINE_POOL` environment variable to be set to true which enables this feature gate to be able to deploy AKS clusters using CAPZ.

EXP_MACHINE_POOL sets --feature-gates=MachinePool=true for the controller manager binary, and it looks like the CAPI operator CRD exposes a spec.manager.featureGates field to do the same thing, but I can't see how to enable this with the helm chart.

/kind feature

**Comment by alexander-demicev** [comment]
Before we fix this issue, it is possible to create a provider secret, before deploying CAPI operator, that will contain this variable:
```
apiVersion: v1
kind: Secret
metadata:
  name: variables
  namespace: default
type: Opaque
stringData:
  CLUSTER_TOPOLOGY: "true"
  EXP_CLUSTER_RESOURCE_SET: "true"
  EXP_MACHINE_POOL: "true"
```
and then reference it using helm options.

**Comment by zioproto** [comment]
I will share my progress here, because it seems there is not a lot of documentation and this could help other people.

This should be the piece of template:

https://github.com/kubernetes-sigs/cluster-api-operator/blob/4ac4c282a45576cd957da23e0d51d9341723c95e/hack/charts/cluster-api-operator/templates/infra.yaml#L41-L52

I tried editing by hand:
```
kubectl apply -f -<<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: variables
  namespace: default
type: Opaque
stringData:
  CLUSTER_TOPOLOGY: "true"
  EXP_CLUSTER_RESOURCE_SET: "true"
  EXP_MACHINE_POOL: "true"
EOF
```

then I had to edit by hand the `infrastructureproviders`:

`kubectl edit infrastructureproviders.operator.cluster.x-k8s.io -n azure-infrastructure-system azure`

I added `configSecret` to the spec ( the `version` was there already).

```
 spec:
   configSecret:
     name: variables
     namespace: default
   version: v1.13.0
```
And I see in the `capz-controller-manager` `Deployment`:

```
spec:
  containers:
  - args:
    - --leader-elect
    - --diagnostics-address=:8443
    - --insecure-diagnostics=false
    - --feature-gates=MachinePool=true,AKSResourceHealth=false,EdgeZone=false
    - --v=0
  ```

Now I tried to do the same with the helm chart.

I tried adding `--set configSecret.name=variables` when installing the Helm chart but it dropped the `version` from the spec.

```
helm upgrade --install capi cluster-api-operator/cluster-api-operator \
    --set infrastructure=azure \
    --set addon=helm --set configSecret.namespace=default --set configSecret.name=variables \
    --set image.manager.tag=v0.8.1 \
    --debug --wait
```

Looking at the code using just `azure` should have never worked! 

I tried then using 

```
helm upgrade --install capi cluster-api-operator/cluster-api-operator \
    --set infrastructure=azure:v1.13.0 \
    --set addon=helm --set configSecret.namespace=default --set configSecret.name=variables \
    --set image.manager.tag=v0.8.1 \
    --debug --wait
```

Now the `infrastructureproviders` looks correct and I also see `--feature-gates=MachinePool=true` in the `capz-controller-manager` `Deployment`
