### ISSUE TITLE
More restrict permissions

### ISSUE THREAD

**Issue by guettli** [kubernetes-sigs/cluster-api-operator#563]
**User Story**

As an operator I would like to have the operator have less RBAC permissions, so that a bug in the operator can't accidentally do bad things.

**Detailed Description**

The role.yaml looks like this at the moment:

https://github.com/kubernetes-sigs/cluster-api-operator/blob/main/config/rbac/role.yaml

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
```

At the moment `manager-role` can do everything. Is this needed?

/kind feature
