### ISSUE TITLE
error message using additionalDeployments field

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-operator#575]
**What steps did you take and what happened:**
```
helm install capi-operator capi-operator/cluster-api-operator --create-namespace -n capi-operator-system --set infrastructure="azure:v1.16.0" --set addon="helm:v0.2.4" --set core="cluster-api:v1.7.4" --set manager.featureGates.core.MachinePool="true" --set manager.featureGates.azure.MachinePool="true" --set additionalDeployments[0]="--crd-pattern=.*" --wait --timeout 90s
```
which produces this error

```
Error: INSTALLATION FAILED: failed post-install: warning: Hook post-install cluster-api-operator/templates/infra.yaml failed: 1 error occurred:
        * admission webhook "vinfrastructureprovider.kb.io" denied the request: json: cannot unmarshal string into Go struct field InfrastructureProviderSpec.spec.additionalDeployments of type v1alpha2.AdditionalDeployments
```

**What did you expect to happen:**
Installation worked and supports the pattern listed.  

**Anything else you would like to add:**
Very possible I just need to pass in the parameter differently for `additionalDeployments` to helm - I just couldn't figure out what that would be.

**Environment:**

- Cluster-api-operator version: 0.12.0
- Cluster-api version: 1.7.4
- Minikube/KIND version: 0.23.0
- Kubernetes version: (use `kubectl version`): 1.30.0
- OS (e.g. from `/etc/os-release`): WSL Ubuntu 22.04

/kind bug

**Comment by willie-yao** [comment]
The additionalDeployments field is a map and has many different nested fields. You're required to specify the name of the deployment, so you'll need a `values.yaml` file. Unfortunately, setting this field from the command line is not possible.

Here's an example of how to use the new field in a `values.yaml` file:
```
additionalDeployments:
  azureserviceoperator-controller-manager:
    deployment:
      containers:
      - name: manager
        args:
          --crd-pattern: "documentdb.azure.com/*;managedidentity.azure.com/*"
```
