### ISSUE TITLE
InfrastructureProvider do not pass configSecret

### ISSUE THREAD

**Issue by k0da** [kubernetes-sigs/cluster-api-operator#592]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
```yaml
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
 name: vsphere
 namespace: capi-system
spec:
 version: v1.10.0
 configSecret:
   name: vsphere-secret
```

```yaml
apiVersion: v1
data:
  VSPHERE_PASSWORD: XXXXXX
  VSPHERE_USERNAME: XXXX
kind: Secret
```

Once provider is installed, resulting bootstrap-secret do not contain provided credentials

```yaml
apiVersion: v1
data:
  credentials.yaml: dXNlcm5hbWU6ICcnCnBhc3N3b3JkOiAnJw==
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vsphere
    clusterctl.cluster.x-k8s.io: ""
  name: capv-manager-bootstrap-credentials
  namespace: capi-system
  ownerReferences:
  - apiVersion: operator.cluster.x-k8s.io/v1alpha2
    kind: InfrastructureProvider
    name: vsphere
    uid: f94a5b43-e7e6-4def-9540-c3d8c178083f
type: Opaque
```
Which is equal to:
```sh
username: ''
password: ''%
```

**What did you expect to happen:**
bootstrap-credentials to contain secret data from spec.configSecret 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-operator version: v0.12.0
- Cluster-api version: v1.8.0
- Minikube/KIND version: --
- Kubernetes version: (use `kubectl version`): 
- Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4+rke2r1
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]

**Comment by k0da** [comment]
I did run `clusterctl generate` and see secret is created properly
```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vsphere
    clusterctl.cluster.x-k8s.io: ""
  name: capv-manager-bootstrap-credentials
  namespace: capv-system
stringData:
  credentials.yaml: |-
    username: 'foo'
    password: 'bar'
type: Opaque
```
