### ISSUE TITLE
Cannot start CAPI providers restricted to a namespace

### ISSUE THREAD

**Issue by serngawy** [kubernetes-sigs/cluster-api-operator#624]
**What steps did you take and what happened:**
create infrastructure Provider ex; CAPA  with setting the container manager args to include a namespace
```
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: aws
  namespace: capa-system
spec:
  configSecret:
    name: capa-manager-bootstrap-credentials
    namespace: capa-system
  deployment:
    containers:
      - command:
          - /manager
        args:
          "--namespace": "capa-system"
        name: manager
  version: v2.6.1
```

**What did you expect to happen:**
 Expect to have the capa provider deployment args assigned with "--namespace" 

**Anything else you would like to add:**
Found the check for the provider args [here](https://github.com/kubernetes-sigs/cluster-api-operator/blob/main/internal/controller/component_customizer.go#L275) ignoring the namespace as argument. 

**Environment:**

- Cluster-api-operator version: 0.14.0
- Cluster-api version: 1.8.2
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): version.Info{Major:"1", Minor:"29", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]
