### ISSUE TITLE
Missing manager featureGates for Bootstrap and ControlPlane Providers

### ISSUE THREAD

**Issue by gcezaralmeida** [kubernetes-sigs/cluster-api-operator#633]
**What steps did you take and what happened:**
It is missing the logic to add the manager.featureGates to the bootstrapProvider and controlplaneProvider in helm template files. In the latest release this can be done only for coreProvider and infraProvider. 

E.g.
```
...
manager:
  featureGates:
    core:
       KubeadmBootstrapFormatIgnition: true 
     bootstrap:                                                     # This one is missing from the template
       KubeadmBootstrapFormatIgnition: true 
     controlplane:                                                 # This one is missing from the template
       KubeadmBootstrapFormatIgnition: true 
...
``` 

**What did you expect to happen:**
Add those manager features gates to the provider Bootstrap and ControlPlane providers.

**Anything else you would like to add:**
I want to contribute to this fix. I will create a PR for this. 

**Environment:**

- Cluster-api-operator version: 0.14.0
- Cluster-api version: 1.8.4
- Minikube/KIND version: 
- Kubernetes version: (use `kubectl version`): Any
- OS (e.g. from `/etc/os-release`): 

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]

**Comment by furkatgofurov7** [comment]
/triage accepted
@gcezaralmeida feel free to assign this and tag me once you open a PR, thanks!

**Comment by jnull** [comment]
I got it working by setting the following:
In your value.yaml:
```
...
manager:
  featureGates:
    core:
      ClusterTopology: "true"
      ClusterResourceSet: "true"
      KubeadmBootstrapFormatIgnition: "true"
configSecret:
  name: config-vars
  namespace: default
...
```
And creating a config secret beforehand:
```
apiVersion: v1
kind: Secret
metadata:
  name: config-vars
  namespace: default
type: Opaque
stringData:
  CLUSTER_TOPOLOGY: "true"
  EXP_KUBEADM_BOOTSTRAP_FORMAT_IGNITION: "true"
  BOOTSTRAP_FORMAT_IGNITION: "true"
```

With that the bootstrap and control-plane provider will take the secret as config and set the correct feature-gates
