### ISSUE TITLE
Operator fails in airgapped envs

### ISSUE THREAD

**Issue by kotyara85** [kubernetes-sigs/cluster-api-operator#639]
Hey there,
Getting this error when installing in airgapped env.
I atteched config files I use
Error:
```
err="failed to read \"metadata.yaml\" from the repository for provider \"cluster-api\": unable to get files for version v1.8.3"
```

```
  kind: CoreProvider
  metadata:
    annotations:
      operator.cluster.x-k8s.io/applied-spec-hash: ""
    labels:
      argocd.argoproj.io/instance: cluster-api-operator
    name: cluster-api
    namespace: capi-system
  spec:
    deployment:
      containers:
      - imageUrl: example.com/cluster-api-controller:v1.8.3
        name: manager
    fetchConfig:
      selector:
        matchLabels:
          provider-components: v1.8.3-cluster-api
    version: v1.8.3
```

All files were downloaded from here - https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.8.3

**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Use config map and core config

**What did you expect to happen:**
Install core componenet

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Attached configmap

**Environment:**

- Cluster-api-operator version:
- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]
 
[cm.zip](https://github.com/user-attachments/files/17928388/cm.zip)
