### ISSUE TITLE
fetchconfig in helm chart not working in airgap environment

### ISSUE THREAD

**Issue by marco210** [kubernetes-sigs/cluster-api-operator#744]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
I used cluster-api-operator helm chart to deploy in airgap environment. I tried uploading provider component to nexus repository and package gitlab but it seems still trying to get manifest from GitHub.
```
E0311 03:30:05.414637       1 controller.go:316] "Reconciler error" err="failed to create repo from provider url for provider \"helm\": error creating the GitHub repository client: failed to get latest release: failed to get repository versions: failed to get repository versions: failed to get the list of releases: context deadline exceeded" controller="addonprovider" controllerGroup="operator.cluster.x-k8s.io" controllerKind="AddonProvider" AddonProvider="helm-addon-system/helm" namespace="helm-addon-system" name="helm" reconcileID="ca97563b-51d4-4c14-a35e-7f490e0b9673"
E0311 03:35:32.514593       1 controller.go:316] "Reconciler error" err="failed to create repo from provider url for provider \"vsphere\": error creating the GitHub repository client: failed to get latest release: failed to get repository versions: failed to get repository versions: failed to get the list of releases: context deadline exceeded" controller="infrastructureprovider" controllerGroup="operator.cluster.x-k8s.io" controllerKind="InfrastructureProvider" InfrastructureProvider="vsphere-infrastructure-system/vsphere" namespace="vsphere-infrastructure-system" name="vsphere" reconcileID="0c98511c-14fe-4cd3-a8e5-24ac2eb8dce1"
E0311 03:36:08.004291       1 controller.go:316] "Reconciler error" err="failed to create repo from provider url for provider \"helm\": error creating the GitHub repository client: failed to get latest release: failed to get repository versions: failed to get repository versions: failed to get the list of releases: Get \"https://api.github.com/repos/kubernetes-sigs/cluster-api-addon-provider-helm/releases?per_page=100\": dial tcp 20.205.243.168:443: i/o timeout" controller="addonprovider" controllerGroup="operator.cluster.x-k8s.io" controllerKind="AddonProvider" AddonProvider="helm-addon-system/helm" namespace="helm-addon-system" name="helm" reconcileID="b58d34c0-9b73-4288-a6b6-ee83a3055c8b"
```
My helm chart value:
```
---
# ---
# Cluster API provider options
core: "cluster-api:v1.9.5"
bootstrap: "kubeadm:v1.9.5"
controlPlane: "kubeadm:v1.9.5"
infrastructure: "vsphere:v1.12.0"
addon: "helm:v0.3.1"
manager.featureGates: {}
fetchConfig: 
  coreProvider: 
    url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/cluster-api/1.9.5/core-components.yaml"
  bootstrapProvider:
    url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/cluster-api/1.9.5/bootstrap-components.yaml"
  controlPlaneProvider:
    url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/cluster-api/1.9.5/control-plane-components.yaml"
  infrastructureProvider:
    url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/vsphere/1.12.0/infrastructure-components.yaml"
  addonProvider:
    url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/cluster-api-addon-provider-helm/v0.3.1/addon-components.yaml"
# ---
# Common configuration secret options
configSecret: 
  name: vsphere-credentials
  namespace: vsphere-infrastructure-system
```

**What did you expect to happen:**
cluster-api-operator get manifest from specificity fetchconfig to run coreProvider, bootstrapProvider,...

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-operator version: v0.17.0
- Cluster-api version: v1.9.5
- Minikube/KIND version: kubeadm 
- Kubernetes version: (use `kubectl version`): v1.28.14
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.4 LTS

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]

**Comment by furkatgofurov7** [comment]
@marco210 I was checking the [code](https://github.com/kubernetes-sigs/cluster-api-operator/blob/1b8ddbd20471a7d0f8506cf88d2e1f352eceba80/util/util.go#L140-L173) and there we have a GitLab check which is regex-based and requires the host to match either `gitlab-.*` or `gitlab.` and the path must start with `/api/v4/projects/`. Can you please check again and make sure `CI_API_V4_URL` does match the above pattern?

**Comment by marco210** [comment]
> [@marco210](https://github.com/marco210) I was checking the [code](https://github.com/kubernetes-sigs/cluster-api-operator/blob/1b8ddbd20471a7d0f8506cf88d2e1f352eceba80/util/util.go#L140-L173) and there we have a GitLab check which is regex-based and requires the host to match either `gitlab-.*` or `gitlab.` and the path must start with `/api/v4/projects/`. Can you please check again and verify if `CI_API_V4_URL` does match the above pattern?

@furkatgofurov7  My `CI_API_V4_URL` (`https://mygit.com/api/v4/projects/`) does not match with `gitlab-.*` or `gitlab.` because my gitlab build self-hosted and the domain is set such as `mygit.com`. Actually, in airgap environment Nexus or Jfrog was used to store the manifests file. Hopefully there is a better way to store and reuse the manifest of providers.

**Comment by Danil-Grigorev** [comment]
@marco210 This functionality is unaltered and comes from `clusterctl`, hard-wired to `github` and `gitlab` URLs. You can prepare `configMaps` for air-gap and provide selector in `fetchConfig`, or use `OCI` repository which is independent from these limitations.

**Comment by marco210** [comment]
@Danil-Grigorev Thank you, I used `OCI` repository and it worked.

**Comment by furkatgofurov7** [comment]
@marco210 hey, feel free to share how did you solve this issue for anyone who might bump into it in the future and close it, thanks!

**Comment by marco210** [comment]
We used `oras`  push provider components to `harbor oci` registry.
```
oras push harbor-registry/capi/kubeadm:v1.9.5 ./bootstrap-components.yaml:application/x-yaml ./metadata.yaml:application/x-yaml
oras push harbor-registry/capi/kubeadm:v1.9.5 ./core-components.yaml:application/x-yaml ./metadata.yaml:application/x-yaml
oras push harbor-registry/capi/kubeadm:v1.9.5 ./controlplane-components.yaml:application/x-yaml ./metadata.yaml:application/x-yaml
```
Below my `value.yaml`
```
---
# ---
# Cluster API provider options
core: "cluster-api:v1.9.5"
bootstrap: "kubeadm:v1.9.5"
controlPlane: "kubeadm:v1.9.5"
infrastructure: "vsphere:v1.12.0"
ipam: "ipam-in-cluster:v1.0.1"
addon: "helm:v0.3.1"
manager.featureGates: {}
fetchConfig:
    vsphere:
      oci: "harbor-registry/capi/vsphere:v1.12.0"
    cluster-api:
      oci: "harbor-registry/capi/kubeadm:v1.9.5"
    kubeadm:
      oci: "harbor-registry/capi/kubeadm:v1.9.5"
    ipam-in-cluster:
      oci: "harbor-registry/capi/ipam-in-cluster:v1.0.1"
    helm: 
      oci: "harbor-registry/capi/helm-provider:v0.3.1"

# ---
# Common configuration secret options
configSecret:
  name: vsphere-credentials
  namespace: vsphere-infrastructure-system
# ---
# CAPI operator deployment options
logLevel: 2
replicaCount: 1
leaderElection:
  enabled: true
image:
  manager:
    repository: registry.k8s.io/capi-operator/cluster-api-operator
    tag: v0.17.0
    pullPolicy: IfNotPresent
env:
  manager: []
diagnosticsAddress: ":8443"
healthAddr: ":9440"
insecureDiagnostics: false
watchConfigSecret: false
imagePullSecrets: {}
resources:
  manager:
    limits:
      cpu: 100m
      memory: 150Mi
    requests:
      cpu: 100m
      memory: 100Mi
containerSecurityContext: {}
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64
                - arm64
                - ppc64le
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
volumes:
  - name: cert
    secret:
      defaultMode: 420
      secretName: capi-operator-webhook-service-cert
volumeMounts:
  manager:
    - mountPath: /tmp/k8s-webhook-server/serving-certs
      name: cert
      readOnly: true

```
We also alter value in helm template(bootstrap, core, controlplane) around fetchConfig
```
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: BootstrapProvider
metadata:
  name: {{ $bootstrapName }}
  namespace: {{ $bootstrapNamespace }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "2"
{{- if or $bootstrapVersion $.Values.configSecret.name $.Values.manager $.Values.additionalDeployments}}
spec:
{{- end}}
{{- if $bootstrapVersion }}
  version: {{ $bootstrapVersion }}
{{- end }}
{{- if and (kindIs "map" $.Values.fetchConfig) (hasKey $.Values.fetchConfig $bootstrapName) }}
{{- range $key, $value := $.Values.fetchConfig }}
  {{- if eq $key $bootstrapName }}
  fetchConfig:
    {{- range $k, $v := $value }}
      {{- toYaml $k | nindent 4 }}: {{ $v }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- if $.Values.configSecret.name }}
  configSecret:
    name: {{ $.Values.configSecret.name }}
    {{- if $.Values.configSecret.namespace }}
    namespace: {{ $.Values.configSecret.namespace }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}

```
