### ISSUE TITLE
Cluster-api-operator not updating resources on ConfigMap changes

### ISSUE THREAD

**Issue by PavanNeerudu** [kubernetes-sigs/cluster-api-operator#795]
## Cluster-api-operator not updating resources on ConfigMap changes

**What steps did you take and what happened:**
We are using `cluster-api-operator` for the lifecycle management of the cluster-api providers. For this, we have custom resources that we want to deploy, and we are using the `InfrastructureProvider` + `ConfigMap` method to install these.

Specifically, our `InfrastructureProvider` looks like this:
```yaml
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: edge
  namespace: cluster-api-edge-system
spec:
  version: v0.1.19
  fetchConfig:
    selector:
      matchLabels:
        provider-components: edge
```

And our ConfigMap looks like this:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    provider-components: edge
  name: v0.1.19
  namespace: cluster-api-edge-system
data:
  components: |
    ...
```

The problem arises when we update something in the ConfigMaps, like CRDs or images. The cluster-api-operator is not updating these resources accordingly on the cluster. According to the documentation, only changes to .spec.version will trigger an upgrade.

**What did you expect to happen:** The cluster-api-operator should update the resources on the cluster when the ConfigMap is updated, even if the version remains the same.

**Anything else you would like to add**: Are there any other ways to achieve this where we update the ConfigMap on the same version of the provider, and the cluster-api-operator will update the resources accordingly?

**Environment**:

Cluster-api-operator version: v0.17.1
Cluster-api version: NA
Minikube/KIND version: NA
Kubernetes version: (use kubectl version) NA
OS (e.g. from /etc/os-release) NA

/kind bug /area cluster-api-operator
