### ISSUE TITLE
LeaderElect passing extra flag

### ISSUE THREAD

**Issue by nikParasyr** [kubernetes-sigs/cluster-api-operator#837]
**What steps did you take and what happened:**
Use the spec.manager.leaderElection as shown below:
```
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  namespace: capi-system
  name: cluster-api
spec:
  version: v1.8.5
  manager:
    leaderElection:
      leaderElect: true
      leaseDuration: 60s
      renewDeadline: 30s
      retryPeriod: 8s
```

This creates the following flags on the container:
```
        - --leader-elect                                   <= this is set by default by the provider
        - --leader-elect=true                              <= this is set by spec.manager.leaderElection 
        - --leader-elect-lease-duration=60s
        - --leader-elect-renew-deadline=30s
        - --leader-elect-retry-period=8s
```

The container still starts without an issue and leaderElection enabled as expected but having double flags is not great.

**What did you expect to happen:**
There shouldnt be a double flag.

**Anything else you would like to add:**
-  When checking here: https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api-operator/operator.cluster.x-k8s.io/CoreProvider/v1alpha2@v0.20.0#spec-manager-leaderElection all the fields are marked as required which makes it not very intuitive. Not sure if this is an issue of the website or of the crds definition, but i can define a subset of the values passed there
- AdditionalArgs can be used instead of leaderElection, to have a single flag:
```
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  namespace: capi-system
  name: cluster-api
spec:
  version: v1.8.5
  manager:
    additionalArgs:
      --leader-elect-lease-duration: 60s
      --leader-elect-renew-deadline: 30s
      --leader-elect-retry-period: 8s
```

**Environment:**

- Cluster-api-operator version: v0.20.0
- Cluster-api version: v1.8.5 but same issue with most (and also infra/addon providers )

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]
